#!/bin/bash
DIR="$(pwd)"
connectionFile=_connFile.txt
pidfile=.pidfile
connectionsFolder=Connections

// check that meshcmd is present
if [[ ! -f ./meshcmd ]]; then
    echo -e "\nCan't find meshcmd\n\n"
    exit 1;
fi

if [[ -f ${1} ]]; then
    sourceFile=${1}
else
    if [[ -f ./${connectionsFolder}/${1} ]]; then
        sourceFile=./${connectionsFolder}/${1}
    else
        more ${connectionFile}
        echo -e "\nUnable to find connection file : ${1}\n"
        exit;
    fi
fi

localPort=$(jq '.localPort' ${sourceFile})
remoteName=$(jq '.remoteName' ${sourceFile})
remotePort=$(jq '.remotePort' ${sourceFile})
password=$(jq '.password' ${sourceFile})
username=$(jq '.username' ${sourceFile})

# remove leading and trailing quotes from variable and ascertain if an infile password is being used
password="${password%\"}"
password="${password#\"}"

if [[ -z ${password} ]]; then
    inFilePassword=0
    # request password from command line
    read -s -p "Please supply password for ${username} : " password
    echo ""
else 
    inFilePassword=1
fi



if [[ "${inFilePassword}" > 0 ]]; then
    # run the meshcmd using infile password, in the background and get its PID
    "${DIR}/meshcmd" --actionfile ${sourceFile} &
    echo $! > ${pidfile}
    pid=`cat ${pidfile}`
    rm ${pidfile}
else
    # run the meshcmd using command line password, in the background and get its PID
    "${DIR}/meshcmd" --actionfile ${sourceFile} --password ${password} &
    echo $! > ${pidfile}
    pid=`cat ${pidfile}`
    rm ${pidfile}
    
fi

if ! [[ -f ${connectionFile} ]]; then
    echo "============================================================" > ${connectionFile}
    echo "  PID   :  Local  :  Connection Details " >> ${connectionFile}
    echo "============================================================" >> ${connectionFile}
    echo " ${pid}  :  ${localPort}  :  ${remoteName} (${remotePort})" >> ${connectionFile}
    echo "" >> ${connectionFile}
    echo "" >> ${connectionFile}
    echo -e "\tUse \"land PID#\" to stop a connection" >> ${connectionFile}
    echo -e "\tUse \"land all\" to stop all connections" >> ${connectionFile}
else
    # get the header
    line1=`head -n3 ${connectionFile}`

    #get the rest of the file
    existing=`tail -n +4 ${connectionFile}`

    # echo out the header
    echo "${line1}" > ${connectionFile}
    
    # add this (latest) entry
    echo " ${pid}  :  ${localPort}  :  ${remoteName} (${remotePort})" >> ${connectionFile}

    # append the rest of the entries
    echo "${existing}" >> ${connectionFile}
fi


more ${connectionFile}
echo ""
echo ""
