#!/bin/bash
DIR="$(pwd)"
connectionFile=_connFile.txt

if [[ "$1" = "all" ]]; then

    echo "Landing all connections"
    for p in `pgrep meshcmd | awk '{print $1}'`; do       # using pgrep prevents "grep --color=auto meshcmd" showing in results
        echo "Stopping ${p}"
        kill ${p}
    done

    rm ${connectionFile}
    exit
fi


# Check that the process requested exists and is a meshcmd process (prevents terminating a valid process that's not meshcmd)
processCheck=$(pgrep meshcmd | grep $1)
if [[ ${processCheck} -ne $1 ]]; then
    more ${connectionFile}
    echo -e "\nProcess $1 is not a meshcmd process, therefore not terminating\n\n"
    exit;
fi


kill $1
sed -i "/$1/d" ${connectionFile}

# get line count from connection file, splitting result by spaces (-d ' ') and returning 1st field (-f1)
lines=`wc -l ${connectionFile} | cut -d ' ' -f1`
if [[ ${lines} -lt 8 ]]; then
    rm ${connectionFile}
    echo -e "\n\tNo more meshcmd connections\n\n"
else
    more ${connectionFile}
    echo ""
    echo ""
fi
